@startuml Ejer1
left to right direction
skinparam packageStyle rectangle
actor socio
actor cliente
actor fabrica
fabrica ..> socio : include
rectangle venta{
    (productos) -- socio : retira
    socio -- (beneficios) : obtienen
    (venta producto) --- socio
    (venta producto) <... (en tienda propia) : extends
    (venta producto) <... (a un socio) : extends
    (venta producto) <... (en tienda de fabrica) : extends
    (venta producto) <... (aplicacion web) : extends
    (beneficios) <. (venta producto) : include
    fabrica -- (productos) : elabora
    cliente -- (aplicacion web) : consultar
    cliente -- (compra producto) 
    (compra producto) -- (venta producto)
}
@enduml